import { StyleSheet } from "react-native";
import { BrightTheme } from "@/constants/Theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BrightTheme.colors.background,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  loadingText: {
    marginTop: 16,
    color: BrightTheme.colors.textSecondary,
    fontSize: 16,
  },
  header: {
    padding: BrightTheme.spacing.lg,
    paddingTop: BrightTheme.spacing.md,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "600",
    color: BrightTheme.colors.textPrimary,
    marginBottom: BrightTheme.spacing.sm,
  },
  headerSubtitle: {
    fontSize: 14,
    color: BrightTheme.colors.textSecondary,
    lineHeight: 22,
  },
  infoButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: BrightTheme.colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  infoButtonText: {
    fontSize: 20,
    color: BrightTheme.colors.textOnPrimary,
    fontWeight: "600",
  },
  summaryCard: {
    margin: 16,
    marginTop: 0,
    padding: 20,
    backgroundColor: BrightTheme.colors.surface,
    borderRadius: 16,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: BrightTheme.colors.textPrimary,
    marginBottom: 8,
  },
  summaryText: {
    fontSize: 14,
    color: BrightTheme.colors.textSecondary,
    lineHeight: 20,
  },
  section: {
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: BrightTheme.colors.textPrimary,
    marginBottom: 12,
  },
  patternCard: {
    backgroundColor: BrightTheme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  patternHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  patternEmoji: {
    fontSize: 32,
    marginRight: 12,
  },
  patternMood: {
    fontSize: 18,
    fontWeight: "600",
    color: BrightTheme.colors.textPrimary,
    flex: 1,
  },
  patternStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: BrightTheme.colors.border,
    borderBottomWidth: 1,
    borderBottomColor: BrightTheme.colors.border,
  },
  patternStat: {
    alignItems: "center",
  },
  patternLabel: {
    fontSize: 12,
    color: BrightTheme.colors.textSecondary,
    marginBottom: 4,
  },
  patternValue: {
    fontSize: 18,
    fontWeight: "700",
    color: BrightTheme.colors.primary,
  },
  patternCondition: {
    marginTop: 12,
    paddingTop: 12,
  },
  patternConditionText: {
    fontSize: 14,
    color: BrightTheme.colors.textSecondary,
    textAlign: "center",
  },
  entryCard: {
    backgroundColor: BrightTheme.colors.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
  },
  entryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: BrightTheme.colors.border,
  },
  entryDate: {
    fontSize: 14,
    fontWeight: "500",
    color: BrightTheme.colors.textSecondary,
  },
  entryMoodEmoji: {
    fontSize: 28,
  },
  entryDetails: {
    gap: 8,
  },
  entryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  entryLabel: {
    fontSize: 14,
    color: BrightTheme.colors.textSecondary,
    fontWeight: "500",
  },
  entryValue: {
    fontSize: 14,
    color: BrightTheme.colors.textPrimary,
    fontWeight: "600",
  },
  emptyStateContainer: {
    padding: 40,
    alignItems: "center",
    marginTop: 40,
  },
  emptyStateIcon: {
    fontSize: 64,
    marginBottom: 20,
  },
  emptyStateText: {
    fontSize: 16,
    color: BrightTheme.colors.textSecondary,
    textAlign: "center",
    lineHeight: 24,
  },
  errorText: {
    color: BrightTheme.colors.error,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: BrightTheme.colors.surface,
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 500,
    maxHeight: "80%",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: BrightTheme.colors.textPrimary,
    marginBottom: 20,
    textAlign: "center",
  },
  modalSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: BrightTheme.colors.textPrimary,
    marginTop: 16,
    marginBottom: 8,
  },
  modalText: {
    fontSize: 14,
    color: BrightTheme.colors.textSecondary,
    lineHeight: 22,
    marginBottom: 8,
  },
  modalCloseButton: {
    backgroundColor: BrightTheme.colors.primary,
    padding: 14,
    borderRadius: BrightTheme.borderRadius.round,
    alignItems: "center",
    marginTop: 20,
  },
  modalCloseButtonText: {
    color: BrightTheme.colors.textOnPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  insightsCard: {
    margin: 16,
    marginTop: 8,
    padding: 20,
    backgroundColor: BrightTheme.colors.surface,
    borderRadius: 16,
  },
  insightRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 12,
    marginBottom: 16,
  },
  insightItem: {
    alignItems: "center",
    flex: 1,
  },
  insightEmoji: {
    fontSize: 36,
    marginBottom: 8,
  },
  insightLabel: {
    fontSize: 12,
    color: BrightTheme.colors.textSecondary,
    marginBottom: 4,
    textAlign: "center",
  },
  insightValue: {
    fontSize: 20,
    fontWeight: "700",
    color: BrightTheme.colors.primary,
  },
  bestWeatherContainer: {
    marginTop: 12,
    padding: 16,
    backgroundColor: BrightTheme.colors.background,
    borderRadius: 12,
  },
  bestWeatherLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: BrightTheme.colors.textPrimary,
    marginBottom: 10,
    textAlign: "center",
  },
  bestWeatherBadge: {
    backgroundColor: BrightTheme.colors.surface,
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  bestWeatherText: {
    fontSize: 18,
    fontWeight: "600",
    color: BrightTheme.colors.textPrimary,
    marginBottom: 4,
  },
  bestWeatherCount: {
    fontSize: 12,
    color: BrightTheme.colors.textSecondary,
  },
});
