import { StyleSheet, Platform } from "react-native";
import { Theme } from "@/constants/ColorPalettes";
import { scaleFontSize, scale } from "@/utils/responsive";

export const createStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    padding: theme.spacing.xl,
    alignItems: "center",
    backgroundColor: theme.colors.background,
  },
  backButton: {
    alignSelf: "flex-start",
    marginBottom: theme.spacing.md,
  },
  backButtonText: {
    fontSize: 16,
    color: theme.colors.primary,
    fontWeight: "600",
  },
  headerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: theme.spacing.sm,
  },
  headerEmoji: {
    fontSize: scaleFontSize(48),
    marginBottom: theme.spacing.sm,
  },
  headerTitle: {
    fontSize: scaleFontSize(24),
    fontWeight: "600",
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.xs,
    textAlign: "center",
  },
  headerDescription: {
    fontSize: scaleFontSize(14),
    color: theme.colors.textSecondary,
    textAlign: "center",
    paddingHorizontal: theme.spacing.lg,
    lineHeight: 20,
  },
  infoButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  infoButtonText: {
    fontSize: 24,
    color: theme.colors.primary,
  },
  chartWrapper: {
    margin: theme.spacing.md,
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    ...theme.shadows.md,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    minHeight: scale(100),
    padding: scale(20),
  },
  centeredText: {
    fontSize: scaleFontSize(16),
    color: theme.colors.textSecondary,
    textAlign: "center",
  },
  errorText: {
    fontSize: scaleFontSize(16),
    color: "#e74c3c",
    textAlign: "center",
  },
  chartSectionTitle: {
    fontSize: scaleFontSize(19),
    fontWeight: "600",
    marginBottom: scale(15),
    color: theme.colors.textPrimary,
  },
  foodListItem: {
    paddingVertical: scale(12),
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  foodListItemLast: {
    borderBottomWidth: 0,
  },
  foodListItemName: {
    fontSize: scaleFontSize(17),
    fontWeight: "600",
    color: theme.colors.textPrimary,
    marginBottom: scale(8),
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: scale(6),
    paddingVertical: scale(2),
  },
  detailLabel: {
    fontSize: scaleFontSize(14),
    color: theme.colors.textSecondary,
  },
  detailValue: {
    fontSize: scaleFontSize(14),
    color: theme.colors.textPrimary,
    fontWeight: "500",
  },
  moodIndicatorRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: scale(8),
  },
  moodIndicatorSwatch: {
    width: scale(18),
    height: scale(18),
    marginLeft: scale(10),
    borderRadius: scale(9),
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  buttonGroup: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  toggleContainer: {
    flexDirection: "row",
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  toggleButtonActive: {
    backgroundColor: theme.colors.primary,
  },
  toggleButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: theme.colors.textSecondary,
  },
  toggleButtonTextActive: {
    color: theme.colors.textOnPrimary,
  },
  foodSelectorButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    backgroundColor: theme.colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 10,
  },
  foodSelectorButtonText: {
    fontSize: 16,
    color: theme.colors.textPrimary,
    flex: 1,
  },
  foodSelectorButtonIcon: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginLeft: 10,
  },
  clearButton: {
    alignSelf: "flex-end",
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#e74c3c",
    borderRadius: 6,
    marginBottom: 10,
  },
  clearButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
    paddingBottom: Platform.OS === "ios" ? 30 : 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: theme.colors.textPrimary,
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseButtonText: {
    fontSize: 20,
    color: theme.colors.textSecondary,
  },
  searchInput: {
    margin: 20,
    marginTop: 15,
    marginBottom: 10,
    padding: 12,
    fontSize: 16,
    backgroundColor: theme.colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    color: theme.colors.textPrimary,
  },
  foodItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  foodItemSelected: {
    backgroundColor: theme.colors.background,
  },
  foodItemText: {
    fontSize: 16,
    color: theme.colors.textPrimary,
  },
  foodItemTextSelected: {
    fontWeight: "600",
    color: theme.colors.primary,
  },
  infoModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  infoModalContainer: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    width: "100%",
    maxHeight: "80%",
    maxWidth: 500,
  },
  infoModalContent: {
    padding: 20,
    maxHeight: 400,
  },
  infoText: {
    fontSize: 15,
    color: theme.colors.textPrimary,
    lineHeight: 22,
    marginBottom: 16,
  },
  colorExplanation: {
    marginVertical: 16,
    padding: 16,
    backgroundColor: theme.colors.background,
    borderRadius: 12,
  },
  colorRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  colorDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  colorLabel: {
    fontSize: 14,
    color: theme.colors.textPrimary,
    flex: 1,
    lineHeight: 20,
  },
  infoNote: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    fontStyle: "italic",
    marginTop: 8,
    padding: 12,
    backgroundColor: theme.colors.background,
    borderRadius: 8,
    lineHeight: 20,
  },
  filterButton: {
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.borderRadius.round,
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  filterButtonActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  filterButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: theme.colors.textSecondary,
  },
  filterButtonTextActive: {
    color: theme.colors.textOnPrimary,
    fontWeight: "600",
  },
  selectedDateDisplay: {
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
    backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
  },
  selectedDateText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textOnPrimary,
  },

  // Impact description styles
  impactDescriptionContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.xs,
  },
  impactDescription: {
    fontSize: 15,
    fontWeight: "600",
    flex: 1,
  },
  impactStars: {
    fontSize: 14,
    letterSpacing: 2,
    color: theme.colors.textSecondary,
  },

  // Progress bar styles
  progressBarContainer: {
    marginVertical: theme.spacing.sm,
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: theme.colors.border,
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 6,
  },
  progressBarFill: {
    height: 6,
    borderRadius: 3,
  },
});
